In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


In [2]:
torch.cuda.is_available()

True

In [6]:
for i in range(4):
    print(f"Using GPU {i}: {torch.cuda.get_device_name(i)}")

Using GPU 0: NVIDIA RTX A6000
Using GPU 1: NVIDIA RTX A6000
Using GPU 2: NVIDIA RTX A6000
Using GPU 3: NVIDIA RTX A6000


## Creating Tensors

In [7]:
# using empty
torch.empty(2,3)

tensor([[1.1488e-12, 4.4057e-41, 1.1488e-12],
        [4.4057e-41, 4.4281e-43, 0.0000e+00]])

- allocates memory, creates a space of the dimension mentioned in the memory.Doesnt assigns any value,since the value already exisits in that space ,it just shows it
- Creates an uninitialized tensor. It allocates memory but does not set values (contains random/garbage data already in memory).

In [8]:
a = torch.empty(3,3)

In [ ]:
type(a)  # Check type

torch.Tensor

In [11]:
# Using Zeros
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

- Creates a tensor filled entirely with zeros.Usually biases value of neural networks can be stored as zeroes inititally.

In [12]:
# Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

- Creates a tensor filled entirely with ones

In [13]:
# Using rand
torch.rand(2,3)

tensor([[0.4719, 0.0888, 0.8321],
        [0.4297, 0.5193, 0.8352]])

- torch.rand(rows, columns): Creates a tensor filled with random numbers from a uniform distribution between 0 and 1.weight intitialization matrix can be initialized with this random numbers.

In [15]:
# Use seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

Sets a fixed seed for generating random numbers. This ensures reproducibility (running the same seed guarantees the exact same random numbers every time).

In [16]:
# Using tensors
torch.tensor([1,3,4])

tensor([1, 3, 4])

torch.tensor(data): Creates a tensor directly from standard Python data structures like lists or nested lists.Creates custom tensor.Basically create a tensor from a python datatype.

In [17]:
# Using arange
torch.arange(1,100,5)

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])

torch.arange(start, end, step): Creates a 1D tensor with a sequence of integers from start up to (but not including) end

In [20]:
# Using linspace
torch.linspace(1,100,3)

tensor([  1.0000,  50.5000, 100.0000])

torch.linspace(start, end, steps): Creates a 1D tensor of evenly (linearly) spaced points between start and end (inclusive). The steps parameter defines exactly how many numbers to generate

- ### Prefer factory functions (zeros, randn, etc.) for speed and correctness vs Python lists.

In [22]:
# Using eye
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

- torch.eye(n): Creates an n x n 2D square identity matrix (contains 1. on the main diagonal and 0. everywhere else).

In [25]:
# Using full
torch.full((3,3),9) # creates a 3x3 matrix where every single element is 9

tensor([[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]])

- torch.full(size, fill_value): Creates a tensor of the specified size (shape) filled entirely with your chosen fill_value

In [26]:
torch.full((6,3),3)

tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])

## Tensor Shapes

In [28]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
x.shape # Returns the dimensions (size) of a tensor.

torch.Size([2, 3])

In [ ]:
x.dtype # Return the data type

torch.int64

In [30]:
x.type()

'torch.LongTensor'

The _like suffix: Functions ending in _like automatically create a new tensor with the exact same shape and data type as an existing reference tensor.

In [34]:
torch.empty_like(x) # Creates an uninitialized tensor matching the shape of the reference.

tensor([[  1271310385153, 103085689576944,              80],
        [             96,     25167404649,              36]])

In [35]:
torch.zeros_like(x) # Creates a tensor filled entirely with zeros matching the shape of the reference.

tensor([[0, 0, 0],
        [0, 0, 0]])

In [36]:
torch.ones_like(x) # Creates a tensor filled entirely with ones matching the shape of the reference.

tensor([[1, 1, 1],
        [1, 1, 1]])

In [37]:
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

- Limitation: Generates a random tensor matching the reference shape, but it requires the reference tensor to be a floating-point data type.X was initialized as int64

## Torch Datatypes

In [ ]:
x.dtype # To know which datatype

torch.int64

In [41]:
t = torch.tensor([1,2,3],dtype = torch.int32)
t

tensor([1, 2, 3], dtype=torch.int32)

In [42]:
t1 = torch.tensor([1.0,2.0,3.0],dtype = torch.int64)
t1

tensor([1, 2, 3])

In [44]:
t2 = torch.tensor([1,23,3],dtype = torch.float32)
t2

tensor([ 1., 23.,  3.])

In [ ]:
# To cast dtype using .to()
t2 = t2.to(torch.int64)
t2

tensor([ 1, 23,  3])

In [47]:
t1 = t1.to(torch.float64)
t1

tensor([1., 2., 3.], dtype=torch.float64)

In [48]:
torch.rand_like(x,dtype = torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

- float32: default training precision (classic)
- float16/bfloat16: common for speed/memory (mixed precision)
- int64: typical for indices / class labels (nn.Embedding, CrossEntropyLoss)

In [49]:
gpu = t1.to("cuda")

In [50]:
print(gpu)

tensor([1., 2., 3.], device='cuda:0', dtype=torch.float64)


In [52]:
cpu = gpu.to("cpu")
print(cpu)

tensor([1., 2., 3.], dtype=torch.float64)


## Mathematical Operations

### 1. Scalar Operation

In [53]:
x = torch.rand(2,3)
x

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [54]:
# addition
x + 2

tensor([[2.7118, 2.7876, 2.4183],
        [2.9014, 2.9969, 2.7565]])

In [55]:
# subtraction
x - 2

tensor([[-1.2882, -1.2124, -1.5817],
        [-1.0986, -1.0031, -1.2435]])

In [56]:
# multiplication
x * 2

tensor([[1.4235, 1.5752, 0.8366],
        [1.8028, 1.9938, 1.5130]])

In [57]:
# division
x / 2

tensor([[0.3559, 0.3938, 0.2092],
        [0.4507, 0.4984, 0.3783]])

In [58]:
# int division
(100*x)//2

tensor([[35., 39., 20.],
        [45., 49., 37.]])

In [59]:
# mod
(100*x)%2

tensor([[1.1765, 0.7581, 1.8305],
        [0.1415, 1.6886, 1.6515]])

In [60]:
# power
x**2

tensor([[0.5066, 0.6203, 0.1750],
        [0.8125, 0.9938, 0.5723]])

### 2. Element wise operation

In [61]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [62]:
print(a)
print(b)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])
tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])


In [63]:
# add
a + b

tensor([[0.6679, 1.2502, 0.9229],
        [1.3130, 0.7983, 1.6774]])

In [64]:
# subtract
a - b

tensor([[-0.2201, -0.6455, -0.5661],
        [ 0.3346,  0.3132,  0.2767]])

In [65]:
# multiply
a * b

tensor([[0.0994, 0.2866, 0.1328],
        [0.4030, 0.1348, 0.6842]])

In [ ]:
# divison
a / b

tensor([[0.5042, 0.3190, 0.2397],
        [1.6841, 2.2912, 1.3951]])

In [ ]:
a // b # int division

tensor([[0., 0., 0.],
        [1., 2., 1.]])

In [68]:
# power
a ** b

tensor([[0.5145, 0.3218, 0.2771],
        [0.9096, 0.8672, 0.9839]])

In [70]:
# mod 
a % b

tensor([[0.2239, 0.3023, 0.1784],
        [0.3346, 0.0706, 0.2767]])

In [71]:
c =  torch.tensor([1,2,-3,4,-5])

In [72]:
# abs (absolute)
torch.abs(c)

tensor([1, 2, 3, 4, 5])

In [73]:
# negative 
torch.neg(c)

tensor([-1, -2,  3, -4,  5])

In [74]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [75]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [76]:
# ceil (to go to the next up integer)
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [77]:
# floor (to go to the lower integer)
torch.floor(d)

tensor([1., 2., 3., 4.])

In [80]:
# clamp : keep numbers in a range

torch.clamp(d,min= 1 ,max=6)


tensor([1.9000, 2.3000, 3.7000, 4.4000])

torch.clamp(): Restricts (or "clamps") the values of a tensor within a specified min and max range. Any value below your defined minimum is forced to the minimum, and any value above your maximum is forced to the maximum. Values already within the bounds remain untouched.
Common Use Case: Preventing exploding gradients during training by capping the gradient values at a safe maximum (a technique known as gradient clipping).

### 3.Reduction Operation

In [97]:
e =  torch.randint(size=(2,3), low = 0, high = 10)
e


tensor([[3, 9, 4],
        [0, 5, 7]])

In [82]:
# sum
torch.sum(e)

tensor(28)

In [83]:
# sum along columns
torch.sum(e,dim = 0)

tensor([16,  5,  7])

In [84]:
# sum along rows
torch.sum(e,dim = 1)

tensor([ 7, 21])

In [85]:
# mean
torch.mean(e)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [86]:
torch.mean(e,dtype=torch.float32)

tensor(4.6667)

In [87]:
# mean along col
torch.mean(e, dim = 0, dtype = torch.float16)

tensor([8.0000, 2.5000, 3.5000], dtype=torch.float16)

In [88]:
# mean along row
torch.mean(e, dim=1, dtype = torch.float64)

tensor([2.3333, 7.0000], dtype=torch.float64)

In [102]:
e = e.to(dtype = torch.float64)

In [103]:
e

tensor([[ 5., 11.,  6.],
        [ 2.,  7.,  9.]], dtype=torch.float64)

In [104]:
# median
torch.median(e)

tensor(6., dtype=torch.float64)

In [105]:
# min and max
torch.max(e)

tensor(11., dtype=torch.float64)

In [106]:
torch.min(e)

tensor(2., dtype=torch.float64)

In [107]:
# product : product of all items
e = e + 2
torch.prod(e)

tensor(288288., dtype=torch.float64)

In [108]:
e

tensor([[ 7., 13.,  8.],
        [ 4.,  9., 11.]], dtype=torch.float64)

In [109]:
# standard deviation
torch.std(e)

tensor(3.1411, dtype=torch.float64)

In [110]:
# variance
torch.var(e)

tensor(9.8667, dtype=torch.float64)

In [111]:
# argmax : tells the position of the max item
torch.argmax(e)

tensor(1)

torch.argmax(): Returns the index (the position) of the maximum value in a tensor. If you apply it across a specific dimension, it tells you where the largest value is located along that axis, rather than returning the value itself.
Common Use Case: Finding the predicted class in a classification model (e.g., looking at an array of 10 probabilities and finding the index of the highest one).

In [112]:
# argmin : telss the positon of the minimum item
torch.argmin(e)

tensor(3)

torch.argmin(): The exact opposite of argmax. It returns the index of the minimum value in a tensor.
Common Use Case: Finding the item with the lowest error or penalty in a given set of calculations.

###  4.Matrix Operations

In [114]:
f =  torch.randint(size = (2,3),low = 0, high = 10)
f

tensor([[5, 9, 9],
        [7, 5, 9]])

In [115]:
g = torch.randint(size = (3,2),low = 0,high = 10)
g

tensor([[8, 9],
        [7, 9],
        [2, 6]])

In [116]:
# matrix multiplication
torch.matmul(f,g)

tensor([[121, 180],
        [109, 162]])

In [117]:
v1 = torch.tensor([1,2])
v2 = torch.tensor([3,4])

In [118]:
# dot product

torch.dot(v1,v2)

tensor(11)

In [ ]:
# transpose (matrix u want to transpose, which dimension it is in, which dimension u want to transpose it)
torch.transpose(g,1,0)

tensor([[8, 7, 2],
        [9, 9, 6]])

In [120]:
torch.t(f)

tensor([[5, 7],
        [9, 5],
        [9, 9]])

In [ ]:
# Inverse and Determinant will work only if we have square matrix
h = torch.randint(size = (3,3), low = 0,high = 10,dtype = torch.float32)
h

tensor([[7., 7., 8.],
        [3., 6., 1.],
        [5., 5., 0.]])

In [122]:
# determinant
torch.det(h)

tensor(-120.)

In [123]:
# inverse
torch.inverse(h)

tensor([[ 0.0417, -0.3333,  0.3417],
        [-0.0417,  0.3333, -0.1417],
        [ 0.1250, -0.0000, -0.1750]])

### 5.Comparision Operations

In [124]:
i = torch.randint(size = (2,3), low = 0, high = 10)
j = torch.randint(size = (2,3), low = 0, high = 10)

In [125]:
i

tensor([[4, 3, 8],
        [8, 3, 3]])

In [126]:
j

tensor([[5, 0, 6],
        [4, 0, 8]])

In [127]:
# greater than
i > j

tensor([[False,  True,  True],
        [ True,  True, False]])

In [128]:
# less than
i < j

tensor([[ True, False, False],
        [False, False,  True]])

In [129]:
i < 4

tensor([[False,  True, False],
        [False,  True,  True]])

In [130]:
i > 5

tensor([[False, False,  True],
        [ True, False, False]])

In [131]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

In [132]:
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [133]:
# greater than equal to
i >= j

tensor([[False,  True,  True],
        [ True,  True, False]])

In [134]:
# smaller than equal to
i <= j

tensor([[ True, False, False],
        [False, False,  True]])

### 6.Special Functions

In [143]:
k =  torch.randint(size = (2,3), low = 1,high = 10)
k

tensor([[6, 3, 9],
        [4, 6, 7]])

In [144]:
# log
torch.log(k)

tensor([[1.7918, 1.0986, 2.1972],
        [1.3863, 1.7918, 1.9459]])

In [145]:
# exponents, exp
torch.exp(k)

tensor([[ 403.4288,   20.0855, 8103.0840],
        [  54.5981,  403.4288, 1096.6332]])

In [146]:
# sqrt
torch.sqrt(k)

tensor([[2.4495, 1.7321, 3.0000],
        [2.0000, 2.4495, 2.6458]])

In [147]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9975, 0.9526, 0.9999],
        [0.9820, 0.9975, 0.9991]])

In [ ]:
# softmax : we have to specifiy along which dimension do we want to apply softmax ; 0 = column ; 1 = row ; expects float values
torch.softmax(k, dim = 1 ,dtype = torch.float32)

tensor([[0.0473, 0.0024, 0.9503],
        [0.0351, 0.2595, 0.7054]])

In [150]:
# relu
torch.relu(k)

tensor([[6, 3, 9],
        [4, 6, 7]])

### Inplace Operations

_ (undescore infront of the function ,represents inplace operation)

In [152]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [153]:
print(m)
print(n)

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])
tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])


In [ ]:
m + n 

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

- Element wise operation creates another tensor and uses up space in the memory

In [155]:
m.add_(n)

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

- here inplace operations stores the value in m

In [156]:
m

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [157]:
n

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [161]:
n = n + 2

In [162]:
torch.relu(n)

tensor([[2.2243, 2.8935, 2.0497],
        [2.1780, 2.3011, 2.1893]])

In [ ]:
n.relu_() # relu inplace and stored inside n itsel

tensor([[2.2243, 2.8935, 2.0497],
        [2.1780, 2.3011, 2.1893]])

In [165]:
x = torch.randn(3, requires_grad=True)
y = x * 2
# x.add_(1)  # may break autograd if x is needed for backward

In-place ops can invalidate values needed for backward, causing errors or wrong grads.
PyTorch often protects you with runtime checks, but don’t rely on it.

### Shape manipulation 

In [167]:
x = torch.randn(4, 8)

x.shape                 # torch.Size([4, 8])

torch.Size([4, 8])

In [168]:
x.view(2, 16)           # reshape (needs contiguous often)

tensor([[-1.0048, -0.8266, -2.2435,  1.9534,  2.8254,  0.4276, -1.1388,  0.2495,
          0.8888,  0.2567, -0.8373, -0.0586,  0.0264,  0.2395,  0.0663,  1.0538],
        [ 0.0384, -0.3326, -0.1593,  0.5721, -0.2678,  1.4583,  0.4207,  0.4938,
         -1.1100, -0.4333,  0.1754,  1.1589,  0.8892, -0.0692,  1.6535,  0.5205]])

.view() may fail on non-contiguous tensors; .reshape() is safer

In [169]:
x.reshape(2, 16)        # safer (may copy if needed)

tensor([[-1.0048, -0.8266, -2.2435,  1.9534,  2.8254,  0.4276, -1.1388,  0.2495,
          0.8888,  0.2567, -0.8373, -0.0586,  0.0264,  0.2395,  0.0663,  1.0538],
        [ 0.0384, -0.3326, -0.1593,  0.5721, -0.2678,  1.4583,  0.4207,  0.4938,
         -1.1100, -0.4333,  0.1754,  1.1589,  0.8892, -0.0692,  1.6535,  0.5205]])

In [ ]:
a = toech.ones(4,4)
a

In [ ]:
a.reshape(2,2,2,2) # Prod of reshape should be same as original
a

In [ ]:
a.flatten()

In [170]:
x.unsqueeze(1)          # add dimension -> [4, 1, 8]

tensor([[[-1.0048, -0.8266, -2.2435,  1.9534,  2.8254,  0.4276, -1.1388,
           0.2495]],

        [[ 0.8888,  0.2567, -0.8373, -0.0586,  0.0264,  0.2395,  0.0663,
           1.0538]],

        [[ 0.0384, -0.3326, -0.1593,  0.5721, -0.2678,  1.4583,  0.4207,
           0.4938]],

        [[-1.1100, -0.4333,  0.1754,  1.1589,  0.8892, -0.0692,  1.6535,
           0.5205]]])

In [ ]:
# image size
c = torch.rand(226,226,3)
c.unsqueeze(2)

In [ ]:
c.unsqueeze(2).shape

In [171]:
x.squeeze()             # remove size-1 dims

tensor([[-1.0048, -0.8266, -2.2435,  1.9534,  2.8254,  0.4276, -1.1388,  0.2495],
        [ 0.8888,  0.2567, -0.8373, -0.0586,  0.0264,  0.2395,  0.0663,  1.0538],
        [ 0.0384, -0.3326, -0.1593,  0.5721, -0.2678,  1.4583,  0.4207,  0.4938],
        [-1.1100, -0.4333,  0.1754,  1.1589,  0.8892, -0.0692,  1.6535,  0.5205]])

In [ ]:
d = torch.rand(1,20)
d.squeeze(0)

In [ ]:
d.squeeze(1).shape

In [172]:
x.transpose(0, 1)       # swap dims

tensor([[-1.0048,  0.8888,  0.0384, -1.1100],
        [-0.8266,  0.2567, -0.3326, -0.4333],
        [-2.2435, -0.8373, -0.1593,  0.1754],
        [ 1.9534, -0.0586,  0.5721,  1.1589],
        [ 2.8254,  0.0264, -0.2678,  0.8892],
        [ 0.4276,  0.2395,  1.4583, -0.0692],
        [-1.1388,  0.0663,  0.4207,  1.6535],
        [ 0.2495,  1.0538,  0.4938,  0.5205]])

In [173]:
x.permute(1, 0)         # reorder dims (general)

tensor([[-1.0048,  0.8888,  0.0384, -1.1100],
        [-0.8266,  0.2567, -0.3326, -0.4333],
        [-2.2435, -0.8373, -0.1593,  0.1754],
        [ 1.9534, -0.0586,  0.5721,  1.1589],
        [ 2.8254,  0.0264, -0.2678,  0.8892],
        [ 0.4276,  0.2395,  1.4583, -0.0692],
        [-1.1388,  0.0663,  0.4207,  1.6535],
        [ 0.2495,  1.0538,  0.4938,  0.5205]])

In [ ]:
b = torch.rand(2,3,4)
b

In [ ]:
b.permute(2,0,1).shape

### Indexing and slicing

In [174]:
x = torch.arange(12).reshape(3, 4)

In [175]:
x[0]        # first row

tensor([0, 1, 2, 3])

In [176]:
x[:, 1]     # second column

tensor([1, 5, 9])

In [177]:
x[1, 2]     # single element tensor

tensor(6)

In [178]:
mask = x > 5
x[mask]     # boolean mask selection

tensor([ 6,  7,  8,  9, 10, 11])

### Copying a Tensor

In [179]:
a = torch.rand(2,3)
a

tensor([[0.1719, 0.9127, 0.6818],
        [0.1953, 0.9991, 0.1133]])

In [ ]:
b = a # Copying using assignment operator

In [181]:
b

tensor([[0.1719, 0.9127, 0.6818],
        [0.1953, 0.9991, 0.1133]])

In [182]:
a[0][0] = 0
a

tensor([[0.0000, 0.9127, 0.6818],
        [0.1953, 0.9991, 0.1133]])

In [ ]:
b 

tensor([[0.0000, 0.9127, 0.6818],
        [0.1953, 0.9991, 0.1133]])

- Changes in original are still visible in copy. By using assignment operation we are not creating a new memory, instead we are referencing the same again

In [187]:
id(a) #id function helps in finding out the memory location

135015050333296

In [188]:
id(b)

135015050333296

In [ ]:
# Using clone : creates a new copy tensor of the same in a new place in memory

b = a.clone()

In [190]:
a

tensor([[0.0000, 0.9127, 0.6818],
        [0.1953, 0.9991, 0.1133]])

In [191]:
b

tensor([[0.0000, 0.9127, 0.6818],
        [0.1953, 0.9991, 0.1133]])

In [192]:
id(a)

135015050333296

In [193]:
id(b)

135015050434800

### Views vs copies
Many ops return views (no new memory), others create copies.
- Quick checks:
- y = x.view(-1)
- y.storage().data_ptr() == x.storage().data_ptr()  # often True for views


- Rules of thumb : view, transpose, permute → usually views (metadata changes)
clone, many advanced indexing patterns → copy

- Why it matters:
Views are memory-efficient, but can surprise you if you modify in-place.


### Tensor Operations on GPU

In [194]:
torch.cuda.is_available()

True

In [195]:
device = torch.device('cuda')

In [196]:
# creating a new tensor on GPU
torch.rand((2,3),device = device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [200]:
# Moving exsiting tensor to GPU
a = torch.rand(size=(2,3))
a

tensor([[0.0135, 0.1450, 0.7819],
        [0.3134, 0.2983, 0.3436]])

In [204]:
b = a.to(device)

In [205]:
b + 10

tensor([[10.0135, 10.1450, 10.7819],
        [10.3134, 10.2983, 10.3436]], device='cuda:0')

In [206]:
import time

In [216]:
size = 10000

In [217]:
# createrandom matrices on cpu
mat_cpu1 = torch.randn(size,size)
mat_cpu2 = torch.randn(size,size)

In [218]:
# Matrix mulplication time on cpu
st_time = time.time()
matmul_cpu = torch.matmul(mat_cpu1,mat_cpu2)
cpu_time = time.time() - st_time

In [219]:
cpu_time

4.8750903606414795

In [220]:
# move matrices to gpu
mat_gpu1 = mat_cpu1.to('cuda')
mat_gpu2 = mat_cpu2.to('cuda')

In [221]:
# matrix multiplication time on gpu
st_time = time.time()
matmul_gpu =  torch.matmul(mat_gpu1,mat_gpu2)
gpu_time = time.time() - st_time

In [222]:
print(cpu_time)
print(gpu_time)

4.8750903606414795
0.10693955421447754


## Numpy

In [223]:
import numpy as np

In [224]:
a =  torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [225]:
b = a.numpy()

In [226]:
type(b)

numpy.ndarray

In [227]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [228]:
torch.from_numpy(c)

tensor([1, 2, 3])